name: Build and Test (Windows)

on:
  push:
    branches: [main, dev]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up CMake
        uses: threeal/cmake-action@v2.1.0

      - name: Configure
        run: cmake -S . -B build -DDESCENT_BUILD_TESTS=ON -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build --config Release

      - name: Prepare test output directory
        run: mkdir build\windows-latest

      - name: Run tests
        run: ctest --test-dir build --output-on-failure -C Release --junit-output build/windows-latest/test-results.xml

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results-windows
          path: build/windows-latest/test-results.xml
