name: Build and Test (Windows)

on:
  push:
    branches: [main, dev]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check CMake version
        run: cmake --version

      - name: Configure
        run: cmake -S . -B build -G "Visual Studio 17 2022" -A x64 -DDESCENT_BUILD_TESTS=ON -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build --config Release --parallel

      - name: Prepare test output directory
        run: mkdir build\windows-latest

      - name: Run tests
        run: ctest --test-dir build --output-on-failure --verbose