name: Build and Test (macOS)

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure
        run: cmake -S . -B build -G "Unix Makefiles" -DDESCENT_BUILD_TESTS=ON -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build --config Release -j$(sysctl -n hw.ncpu)

      - name: Run tests
        run: ctest --test-dir build --output-on-failure --verbose
