name: Build and Test (macOS)

on:
  push:
    branches: [main, dev]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check CMake version
        run: cmake --version

      - name: Configure
        run: cmake -S . -B build -G "Unix Makefiles" -DDESCENT_BUILD_TESTS=ON -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build --config Release -j$(nproc)

      - name: Prepare test output directory
        run: mkdir -p build/macos-latest

      - name: Run tests
        run: ctest --test-dir build --output-on-failure --junit-output build/macos-latest/test-results.xml

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results-macos
          path: build/macos-latest/test-results.xml
